(function(){
  "use strict";
  var e=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c];});};
  function field(label,id,value,options){options=options||{};var cls=options.full?"field full":"field",required=options.required?" required":"",control;
    if(options.type==="textarea")control='<textarea id="'+id+'">'+e(value)+'</textarea>';
    else if(options.values)control='<select id="'+id+'">'+options.values.map(function(v){return'<option'+(v===value?" selected":"")+'>'+e(v)+'</option>';}).join("")+"</select>";
    else control='<input id="'+id+'" value="'+e(value)+'" '+(options.readonly?'readonly class="readonly"':"")+'>';
    return'<div class="'+cls+'"><label class="'+required+'" for="'+id+'">'+e(label)+'</label>'+control+(options.help?'<small>'+e(options.help)+'</small>':"")+"</div>";
  }
  function validation(step,state){var r=window.CMMS_VALIDATIONS.validate(step,state);return'<div class="validation-box'+(r.valid?"":" error")+'"><strong>'+(r.valid?"Etapa completa":"Requiere atención")+'</strong>'+(r.valid?"<span>Las reglas disponibles para P04.2 están superadas.</span>":"<ul>"+r.errors.map(function(x){return"<li>"+e(x)+"</li>";}).join("")+"</ul>")+"</div>";}
  function shell(step,state,body){var meta=window.CMMS_CATALOGS.steps[step];return'<section class="step-view"><header class="step-heading"><div><span class="eyebrow">Paso '+step+" · Núcleo AMEF</span><h1>"+e(meta.question)+"</h1><p>"+e(meta.why)+'</p></div><span class="stage-badge">Implementado · P04.2</span></header>'+body+'<button class="link-button" type="button" data-rules>Ver datos y reglas</button></section>';}
  function scope(state){
    var h=state.analysisHeader,c=state.operationalContext;
    var body='<div class="form-layout"><section class="form-panel"><h2>Cabecera y contexto operacional</h2><div class="form-grid">'+
      field("Código","scopeCode",h.id,{readonly:true})+field("Revisión","scopeRevision",h.revision,{readonly:true})+
      field("Título","scopeTitle",h.title,{required:true,full:true})+field("Tipo de análisis","scopeType",h.analysisType,{values:["Tipo de equipo","Familia","Sistema","Activo"]})+
      field("Servicio","scopeService",c.service,{required:true})+field("Régimen","scopeRegime",c.regime,{values:["Continuo","Intermitente","Reserva"]})+field("Redundancia","scopeConfig",c.configuration)+
      field("Contexto operacional","scopeContext",c.context,{type:"textarea",required:true,full:true})+field("Fuentes técnicas","scopeSource",c.source,{type:"textarea",full:true})+field("Supuestos","scopeAssumptions",c.assumptions,{type:"textarea",full:true})+
      '</div><div class="form-actions"><button id="saveScope" class="button button-primary" type="button">Guardar alcance</button></div></section><aside class="support-panel"><h2>Estructuras relacionadas</h2><div class="structure-strip"><div class="structure-item"><strong>Taxonomía · Qué es</strong><span>'+e(h.taxonomyScope)+'</span></div><div class="structure-item"><strong>FLH · Dónde opera</strong><span>'+e(c.flh)+'</span></div><div class="structure-item"><strong>ADR · Composición física</strong><span>Raíz '+e(c.adrRoot)+" · "+e(c.relatedAssets.join(", "))+'</span></div></div><div style="margin-top:14px">'+validation(1,state)+"</div></aside></div>";
    return shell(1,state,body);
  }
  function functionsView(state){
    var selected=findFunction(state,state.uiState.selectedFunctionId)||state.functions[0]||{id:"",description:"",type:"Primaria",performanceStandard:"",value:"",unit:"m³/h",tolerance:"",condition:"",source:"",qualitativeReason:""};
    var rows=state.functions.map(function(fn){return'<tr><td><strong>'+e(fn.id)+'</strong></td><td>'+e(fn.description)+'</td><td>'+e(fn.type)+'</td><td>'+e(fn.performanceStandard)+'</td><td>'+(fn.functionalFailures||[]).length+'</td><td><button class="row-action" type="button" data-select-function="'+e(fn.id)+'">Editar</button></td></tr>';}).join("");
    var body='<div class="form-layout"><section class="form-panel"><h2>Definición de función</h2><input id="functionId" type="hidden" value="'+e(selected.id)+'"><div class="form-grid">'+field("Descripción","functionDescription",selected.description,{required:true,full:true,help:"Comienza con un verbo de acción."})+field("Tipo","functionType",selected.type,{values:["Primaria","Secundaria","Protección","Ambiental","Otra"]})+field("Estándar de desempeño","functionStandard",selected.performanceStandard,{required:true,full:true})+field("Valor","functionValue",selected.value)+field("Unidad","functionUnit",selected.unit,{values:["m³/h","bar","°C","%","Cualitativo"]})+field("Condición operacional","functionCondition",selected.condition)+field("Fuente","functionSource",selected.source,{full:true})+'</div><div class="form-actions"><button id="newFunction" class="button button-secondary" type="button">Nueva función</button><button id="saveFunction" class="button button-primary" type="button">Guardar función</button></div></section><aside class="support-panel"><h2>Completitud</h2>'+validation(2,state)+'</aside></div><section class="tree-panel"><h2>Funciones del análisis</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Función</th><th>Tipo</th><th>Estándar</th><th>Fallos</th><th></th></tr></thead><tbody>'+rows+"</tbody></table></div></section>";
    return shell(2,state,body);
  }
  function failuresView(state){
    var all=allFailures(state),selected=findFailure(state,state.uiState.selectedFailureId)||(all[0]&&all[0].failure)||{id:"",functionId:(state.functions[0]||{}).id||"",type:"Pérdida total",description:"",detectionCondition:""};
    var functionOptions=state.functions.map(function(fn){return{id:fn.id,label:fn.id+" · "+fn.description};});
    var rows=all.map(function(x){return'<tr><td>'+e(x.fn.id)+'</td><td><strong>'+e(x.failure.id)+'</strong><br>'+e(x.failure.description)+'</td><td>'+e(x.failure.type)+'</td><td>'+(x.failure.failureModes||[]).length+'</td><td><button class="row-action" type="button" data-select-failure="'+e(x.failure.id)+'">Editar</button></td></tr>';}).join("");
    var fnSelect='<div class="field"><label class="required" for="failureFunction">Función</label><select id="failureFunction">'+functionOptions.map(function(x){return'<option value="'+e(x.id)+'"'+(x.id===selected.functionId?" selected":"")+'>'+e(x.label)+'</option>';}).join("")+"</select></div>";
    var body='<div class="form-layout"><section class="form-panel"><h2>Incumplimiento de una función</h2><input id="failureId" type="hidden" value="'+e(selected.id)+'"><div class="form-grid">'+fnSelect+field("Tipo de fallo","failureType",selected.type,{values:["Pérdida total","Pérdida parcial","Intermitente","Fuera de límite","No demandada"]})+field("Descripción","failureDescription",selected.description,{required:true,full:true,help:"Describe el incumplimiento, no la pieza averiada ni la causa."})+field("Condición de detección","failureDetection",selected.detectionCondition,{full:true})+'</div><div class="form-actions"><button id="newFailure" class="button button-secondary" type="button">Nuevo fallo</button><button id="saveFailure" class="button button-primary" type="button">Guardar fallo</button></div></section><aside class="support-panel"><h2>Regla estructural</h2><p class="muted">Todo fallo pertenece a una función. El vínculo se conserva por ID aunque cambie la descripción.</p>'+validation(3,state)+'</aside></div><section class="tree-panel"><h2>Función → fallo funcional</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Función</th><th>Fallo funcional</th><th>Tipo</th><th>Modos</th><th></th></tr></thead><tbody>'+rows+"</tbody></table></div></section>";
    return shell(3,state,body);
  }
  function modesView(state){
    var modes=allModes(state),selected=findMode(state,state.uiState.selectedModeId)||(modes[0]&&modes[0].mode),parent=modes.filter(function(x){return selected&&x.mode.id===selected.id;})[0],tabs=modes.map(function(x){return'<button class="mode-tab'+(selected&&x.mode.id===selected.id?" active":"")+'" data-select-mode="'+e(x.mode.id)+'" type="button">'+e(x.mode.id)+" · "+(x.mode.hidden?"Fallo oculto":"Modo principal")+"</button>";}).join("");
    if(!selected)return shell(4,state,'<div class="empty-state">Crea primero un fallo funcional y un modo.</div>');
    var causes=(selected.causes||[]).map(function(x){return x.description;}).join("\n"),effects=(selected.effects||[]).map(function(x){return x.level+" | "+x.description;}).join("\n");
    var body='<div class="mode-switcher">'+tabs+'</div><div class="form-layout"><section class="form-panel"><h2>Modo, causas y efectos</h2><input id="modeId" type="hidden" value="'+e(selected.id)+'"><div class="form-grid">'+field("Fallo funcional","modeParent",(parent?parent.failure.id:""),{readonly:true})+field("Condición","modeHidden",selected.hidden?"Oculto":"Evidente",{values:["Evidente","Oculto"]})+field("Modo de fallo","modeDescription",selected.description,{type:"textarea",required:true,full:true})+field("Mecanismo","modeMechanism",selected.mechanism,{full:true})+field("Detectabilidad","modeDetectability",selected.detectability)+field("Velocidad de degradación","modeSpeed",selected.degradationSpeed)+field("Causas","modeCauses",causes,{type:"textarea",full:true,help:"Una causa por línea."})+field("Efectos","modeEffects",effects,{type:"textarea",required:true,full:true,help:"Formato: nivel | descripción. Un efecto por línea."})+'</div><div class="form-actions"><button id="saveMode" class="button button-primary" type="button">Guardar modo</button></div></section><aside class="support-panel"><h2>Completitud del AMEF</h2><p class="muted">Separa señales observables de consecuencias empresariales. El riesgo se evaluará en P04.3.</p>'+validation(4,state)+'</aside></div><section class="tree-panel"><h2>Árbol AMEF navegable</h2>'+renderTree(state)+'</section>';
    return shell(4,state,body);
  }
  function renderTree(state){
    var html='<div class="fmea-tree">';
    state.functions.forEach(function(fn){html+=node(0,"Función · "+fn.id,fn.description);(fn.functionalFailures||[]).forEach(function(ff){html+=node(1,"Fallo funcional · "+ff.id,ff.description);(ff.failureModes||[]).forEach(function(m){html+=node(2,(m.hidden?"Modo oculto":"Modo")+" · "+m.id,m.description);(m.causes||[]).forEach(function(c){html+=node(3,"Causa · "+c.id,c.description);});(m.effects||[]).forEach(function(x){html+=node(3,"Efecto "+x.level+" · "+x.id,x.description);});});});});
    return html+"</div>";
  }
  function node(depth,type,text){return'<div class="tree-node depth-'+depth+'" style="--depth:'+(depth*22)+'px"><span class="node-type">'+e(type)+'</span><p>'+e(text)+'</p></div>';}
  function findFunction(state,id){return state.functions.filter(function(x){return x.id===id;})[0];}
  function allFailures(state){var out=[];state.functions.forEach(function(fn){(fn.functionalFailures||[]).forEach(function(f){out.push({fn:fn,failure:f});});});return out;}
  function findFailure(state,id){var x=allFailures(state).filter(function(x){return x.failure.id===id;})[0];return x&&x.failure;}
  function allModes(state){var out=[];allFailures(state).forEach(function(x){(x.failure.failureModes||[]).forEach(function(m){out.push({fn:x.fn,failure:x.failure,mode:m});});});return out;}
  function findMode(state,id){var x=allModes(state).filter(function(x){return x.mode.id===id;})[0];return x&&x.mode;}
  function value(id){return document.getElementById(id).value.trim();}
  function lines(text){return text.split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);}
  function bind(step,state,refresh,notify){
    function on(id,event,handler){var x=document.getElementById(id);if(x)x.addEventListener(event,handler);}
    document.querySelectorAll("[data-select-function]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedFunctionId=b.dataset.selectFunction;refresh();});});
    document.querySelectorAll("[data-select-failure]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedFailureId=b.dataset.selectFailure;refresh();});});
    document.querySelectorAll("[data-select-mode]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedModeId=b.dataset.selectMode;refresh();});});
    on("saveScope","click",function(){Object.assign(state.analysisHeader,{title:value("scopeTitle"),analysisType:value("scopeType")});Object.assign(state.operationalContext,{service:value("scopeService"),regime:value("scopeRegime"),configuration:value("scopeConfig"),context:value("scopeContext"),source:value("scopeSource"),assumptions:value("scopeAssumptions")});commit("Alcance actualizado.");});
    on("newFunction","click",function(){state.uiState.selectedFunctionId="";document.getElementById("functionId").value="";["functionDescription","functionStandard","functionValue","functionSource"].forEach(function(id){document.getElementById(id).value="";});document.getElementById("functionDescription").focus();});
    on("saveFunction","click",function(){var id=value("functionId"),fn=findFunction(state,id);if(!fn){id="FUN-"+String(state.functions.length+1).padStart(3,"0");fn={id:id,functionalFailures:[]};state.functions.push(fn);}Object.assign(fn,{description:value("functionDescription"),type:value("functionType"),performanceStandard:value("functionStandard"),value:value("functionValue"),unit:value("functionUnit"),condition:value("functionCondition"),source:value("functionSource"),qualitativeReason:""});state.uiState.selectedFunctionId=id;commit("Función guardada.");});
    on("newFailure","click",function(){state.uiState.selectedFailureId="";document.getElementById("failureId").value="";document.getElementById("failureDescription").value="";document.getElementById("failureDetection").value="";document.getElementById("failureDescription").focus();});
    on("saveFailure","click",function(){var id=value("failureId"),fn=findFunction(state,value("failureFunction")),ff=findFailure(state,id);if(!fn)return notify("Selecciona una función válida.");if(!ff){id="FF-"+String(allFailures(state).length+1).padStart(3,"0");ff={id:id,failureModes:[]};fn.functionalFailures.push(ff);}Object.assign(ff,{functionId:fn.id,type:value("failureType"),description:value("failureDescription"),detectionCondition:value("failureDetection")});state.uiState.selectedFailureId=id;commit("Fallo funcional guardado.");});
    on("saveMode","click",function(){var mode=findMode(state,value("modeId"));if(!mode)return;Object.assign(mode,{description:value("modeDescription"),mechanism:value("modeMechanism"),detectability:value("modeDetectability"),degradationSpeed:value("modeSpeed"),hidden:value("modeHidden")==="Oculto"});mode.causes=lines(value("modeCauses")).map(function(text,i){return{id:"CAU-"+mode.id.slice(3)+"-"+(i+1),description:text,category:"Pendiente de clasificar",control:"",evidence:""};});mode.effects=lines(value("modeEffects")).map(function(text,i){var parts=text.split("|");return{id:"EFF-"+mode.id.slice(3)+"-"+(i+1),level:(parts.shift()||"Local").trim(),description:parts.join("|").trim()||text};});commit("Modo, causas y efectos guardados.");});
    function commit(message){window.CMMS_STORE.markDirty();refresh();notify(message);}
  }
  window.CMMS_P042={render:function(step,state){return({1:scope,2:functionsView,3:failuresView,4:modesView})[step](state);},bind:bind,validate:function(step,state){return window.CMMS_VALIDATIONS.validate(step,state);}};
})();
