(function(){
  "use strict";
  var catalogs=window.CMMS_P043_CATALOGS,e=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c];});};
  function allModes(state){var out=[];state.functions.forEach(function(fn){fn.functionalFailures.forEach(function(ff){ff.failureModes.forEach(function(mode){out.push({fn:fn,failure:ff,mode:mode});});});});return out;}
  function mode(state,id){return allModes(state).filter(function(x){return x.mode.id===id;})[0]||allModes(state)[0];}
  function tabs(state,selectedId,attr){return'<div class="mode-switcher">'+allModes(state).map(function(x){return'<button type="button" class="mode-tab'+(x.mode.id===selectedId?" active":"")+'" '+attr+'="'+e(x.mode.id)+'">'+e(x.mode.id)+" · "+(x.mode.hidden?"Fallo oculto":"Modo principal")+"</button>";}).join("")+"</div>";}
  function shell(step,body){var meta=window.CMMS_CATALOGS.steps[step];return'<section class="step-view"><header class="step-heading"><div><span class="eyebrow">Paso '+step+" · Riesgo y RCM</span><h1>"+e(meta.question)+"</h1><p>"+e(meta.why)+'</p></div><span class="stage-badge">Implementado · P04.3</span></header>'+body+'<button class="link-button" type="button" data-rules>Ver datos y reglas</button></section>';}
  function select(label,id,value,items){return'<div class="field"><label for="'+id+'">'+e(label)+'</label><select id="'+id+'">'+items.map(function(x){var val=x.value==null?x:x.value,label=x.label==null?x:x.value+" · "+x.label;return'<option value="'+e(val)+'"'+(String(val)===String(value)?" selected":"")+'>'+e(label)+'</option>';}).join("")+"</select></div>";}
  function textarea(label,id,value,required){return'<div class="field full"><label class="'+(required?"required":"")+'" for="'+id+'">'+e(label)+'</label><textarea id="'+id+'">'+e(value)+'</textarea></div>';}
  function modeContext(x){return'<div class="mode-context"><div><strong>'+e(x.mode.id)+" · "+e(x.failure.id)+'</strong><p>'+e(x.mode.description)+'</p></div><span class="mini-badge">'+(x.mode.hidden?"Oculto":"Evidente")+"</span></div>";}
  function risk(state){
    var x=mode(state,state.uiState.selectedRiskModeId),a=x.mode.consequenceAssessment,inh=window.CMMS_RISK_ENGINE.calculate(a.severity,a.probability),res=window.CMMS_RISK_ENGINE.calculate(a.residualSeverity,a.residualProbability),check=window.CMMS_RISK_ENGINE.validate(a);
    var dims=[["Seguridad","riskSafety","safety"],["Medioambiente","riskEnvironment","environment"],["Operación/producción","riskOperation","operation"],["Calidad","riskQuality","quality"],["Coste directo","riskCost","directCost"],["No operacional","riskNonOperational","nonOperational"]].map(function(d){return select(d[0],d[1],a.dimensions[d[2]],["Baja","Moderada","Alta","Crítica"]);}).join("");
    var body=tabs(state,x.mode.id,"data-risk-mode")+modeContext(x)+'<div class="risk-layout"><section class="form-panel"><h2>Consecuencias y puntuación</h2><div class="dimension-grid">'+dims+'</div><div class="form-grid" style="margin-top:14px">'+select("Severidad inherente","riskSeverity",a.severity,catalogs.risk.severity)+select("Probabilidad inherente","riskProbability",a.probability,catalogs.risk.probability)+textarea("Justificación inherente","riskJustification",a.justification,true)+textarea("Salvaguardas actuales","riskSafeguards",a.safeguards,false)+select("Severidad residual","riskResidualSeverity",a.residualSeverity,catalogs.risk.severity)+select("Probabilidad residual","riskResidualProbability",a.residualProbability,catalogs.risk.probability)+textarea("Justificación residual","riskResidualJustification",a.residualJustification,true)+'</div><div class="form-actions"><button id="saveRisk" class="button button-primary" type="button">Guardar evaluación</button></div></section><aside class="support-panel"><h2>Matriz 5 x 5</h2><div class="risk-score-band"><div class="risk-score"><span>Riesgo inherente</span><strong>'+inh.score+'</strong><span class="risk-level '+inh.level.className+'">'+inh.level.label+'</span></div><div class="risk-score"><span>Riesgo residual</span><strong>'+res.score+'</strong><span class="risk-level '+res.level.className+'">'+res.level.label+'</span></div></div>'+matrix(a)+'<div class="config-note"><strong>'+e(catalogs.risk.version)+":</strong> "+e(catalogs.risk.disclaimer)+'</div><div style="margin-top:12px">'+validation(check)+"</div></aside></div>";
    return shell(5,body);
  }
  function matrix(a){var html='<div class="matrix-shell"><div class="matrix-y">Severidad</div><div class="risk-matrix">';for(var s=5;s>=1;s--){for(var p=1;p<=5;p++){var score=s*p,l=window.CMMS_RISK_ENGINE.calculate(s,p).level.className,cls=(s===Number(a.severity)&&p===Number(a.probability)?" inherent":"")+(s===Number(a.residualSeverity)&&p===Number(a.residualProbability)?" residual":"");html+='<div class="risk-cell '+l+cls+'" title="Severidad '+s+', probabilidad '+p+'">'+score+"</div>";}}return html+'</div><div class="matrix-x">Probabilidad</div></div>';}
  function validation(check){return'<div class="validation-box'+(check.valid?"":" error")+'"><strong>'+(check.valid?"Evaluación completa":"Requiere atención")+'</strong>'+(check.valid?"<span>La puntuación conserva versión y justificación.</span>":"<ul>"+check.errors.map(function(x){return"<li>"+e(x)+"</li>";}).join("")+"</ul>")+"</div>";}
  function rcm(state){
    var x=mode(state,state.uiState.selectedRcmModeId),a=x.mode.rcmAssessment,selectedId=state.uiState.selectedRcmQuestionId||"Q1",q=catalogs.rcm.questions.filter(function(q){return q.id===selectedId;})[0]||catalogs.rcm.questions[0],response=a.responses[q.id]||{answer:"",explanation:"",evidence:"",user:"Laura Martín · Fiabilidad",date:"2026-07-30"},check=window.CMMS_RCM_ENGINE.validate(a),recommendation=check.recommendation;
    var questions=catalogs.rcm.questions.map(function(item){var r=a.responses[item.id],ans=r&&r.answer;return'<button class="question-card'+(item.id===q.id?" active":"")+'" type="button" data-rcm-question="'+item.id+'"><span class="answer-state">'+e(ans||"Pendiente")+'</span><strong>'+item.id+" · "+e(item.plain)+'</strong><span>'+e(item.technical)+'</span></button>';}).join("");
    var answers=catalogs.rcm.answers.map(function(ans){return'<button type="button" class="answer-option'+(response.answer===ans?" active":"")+'" data-answer="'+e(ans)+'">'+e(ans)+"</button>";}).join("");
    var body=tabs(state,x.mode.id,"data-rcm-mode")+modeContext(x)+'<div class="rcm-layout"><aside class="support-panel"><h2>Árbol de preguntas</h2><div class="question-list">'+questions+'</div><div class="config-note">Versión del árbol: <strong>'+e(catalogs.rcm.version)+'</strong></div></aside><section class="form-panel"><span class="eyebrow">'+q.id+" · Lenguaje sencillo</span><h2>"+e(q.plain)+'</h2><div class="technical-copy"><strong>Formulación técnica:</strong> '+e(q.technical)+'</div><div class="answer-options">'+answers+'</div><div class="form-grid">'+textarea("Explicación","rcmExplanation",response.explanation,true)+textarea("Evidencia","rcmEvidence",response.evidence,true)+'</div><div class="form-actions"><button id="saveRcmResponse" class="button button-primary" type="button">Guardar respuesta</button></div><div class="rcm-result"><span class="eyebrow">Resultado reproducible</span><div class="result-diff"><div class="result-item"><span>Recomendación</span><strong>'+e(recommendation)+'</strong></div><div class="result-item"><span>Decisión adoptada</span><strong>'+e(a.override?a.adoptedDecision:recommendation)+'</strong></div></div><div class="rcm-path">'+catalogs.rcm.questions.map(function(item){return'<span class="path-node'+(a.responses[item.id]&&a.responses[item.id].answer?"":" pending")+'">'+item.id+"</span>";}).join("")+'</div><div class="override-box"><label class="check-row"><input id="rcmOverride" type="checkbox" '+(a.override?"checked":"")+'> Adoptar una decisión distinta</label><div class="form-grid" style="margin-top:11px">'+select("Decisión adoptada","rcmAdoptedDecision",a.adoptedDecision,catalogs.rcm.results)+textarea("Motivo del override","rcmOverrideReason",a.overrideReason,a.override)+'</div><div class="form-actions"><button id="saveRcmDecision" class="button button-secondary" type="button">Guardar decisión</button></div></div><div style="margin-top:12px">'+validationRcm(check)+'</div></div></section></div>';
    return shell(6,body);
  }
  function validationRcm(check){return'<div class="validation-box'+(check.valid?"":" error")+'"><strong>'+(check.valid?"Recorrido consistente":"Recorrido incompleto")+'</strong>'+(check.valid?"<span>Respuestas, evidencia y resultado quedan trazados.</span>":"<ul>"+check.errors.map(function(x){return"<li>"+e(x)+"</li>";}).join("")+"</ul>")+"</div>";}
  function value(id){var node=document.getElementById(id);return node?node.value.trim():"";}
  function bind(step,state,refresh,notify){
    document.querySelectorAll("[data-risk-mode]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedRiskModeId=b.dataset.riskMode;refresh();});});
    document.querySelectorAll("[data-rcm-mode]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedRcmModeId=b.dataset.rcmMode;state.uiState.selectedRcmQuestionId="Q1";refresh();});});
    document.querySelectorAll("[data-rcm-question]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedRcmQuestionId=b.dataset.rcmQuestion;refresh();});});
    document.querySelectorAll("[data-answer]").forEach(function(b){b.addEventListener("click",function(){document.querySelectorAll("[data-answer]").forEach(function(x){x.classList.remove("active");});b.classList.add("active");b.parentElement.dataset.selected=b.dataset.answer;});});
    var saveRisk=document.getElementById("saveRisk");if(saveRisk)saveRisk.addEventListener("click",function(){var x=mode(state,state.uiState.selectedRiskModeId),a=x.mode.consequenceAssessment;a.dimensions={safety:value("riskSafety"),environment:value("riskEnvironment"),operation:value("riskOperation"),quality:value("riskQuality"),directCost:value("riskCost"),nonOperational:value("riskNonOperational")};Object.assign(a,{severity:Number(value("riskSeverity")),probability:Number(value("riskProbability")),residualSeverity:Number(value("riskResidualSeverity")),residualProbability:Number(value("riskResidualProbability")),justification:value("riskJustification"),safeguards:value("riskSafeguards"),residualJustification:value("riskResidualJustification"),matrixVersion:catalogs.risk.version});commit("Evaluación de riesgo guardada.");});
    var saveResponse=document.getElementById("saveRcmResponse");if(saveResponse)saveResponse.addEventListener("click",function(){var x=mode(state,state.uiState.selectedRcmModeId),a=x.mode.rcmAssessment,qid=state.uiState.selectedRcmQuestionId,selected=document.querySelector(".answer-options").dataset.selected||((a.responses[qid]||{}).answer)||"";a.responses[qid]={answer:selected,explanation:value("rcmExplanation"),evidence:value("rcmEvidence"),user:"Laura Martín · Fiabilidad",date:"2026-07-30"};a.recommendation=window.CMMS_RCM_ENGINE.recommendation(a);if(!a.override)a.adoptedDecision=a.recommendation;commit("Respuesta RCM guardada.");});
    var saveDecision=document.getElementById("saveRcmDecision");if(saveDecision)saveDecision.addEventListener("click",function(){var a=mode(state,state.uiState.selectedRcmModeId).mode.rcmAssessment;a.override=document.getElementById("rcmOverride").checked;a.adoptedDecision=value("rcmAdoptedDecision");a.overrideReason=value("rcmOverrideReason");var check=window.CMMS_RCM_ENGINE.validate(a);if(!check.valid&&a.override&&!a.overrideReason)return notify("Justifica el override antes de guardar.");commit("Decisión RCM guardada.");});
    function commit(message){window.CMMS_STORE.markDirty();refresh();notify(message);}
  }
  window.CMMS_P043={render:function(step,state){return step===5?risk(state):rcm(state);},bind:bind,validate:function(step,state){var x=mode(state,step===5?state.uiState.selectedRiskModeId:state.uiState.selectedRcmModeId);return step===5?window.CMMS_RISK_ENGINE.validate(x.mode.consequenceAssessment):window.CMMS_RCM_ENGINE.validate(x.mode.rcmAssessment);}};
})();
