(function(){
  "use strict";
  var catalogs=window.CMMS_P044_CATALOGS,e=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c];});};
  function allModes(state){var out=[];state.functions.forEach(function(fn){fn.functionalFailures.forEach(function(ff){ff.failureModes.forEach(function(mode){out.push({fn:fn,failure:ff,mode:mode});});});});return out;}
  function field(label,id,value,options){options=options||{};var values=options.values,control;if(options.type==="textarea")control='<textarea id="'+id+'">'+e(value)+'</textarea>';else if(values)control='<select id="'+id+'">'+values.map(function(x){return'<option'+(x===value?" selected":"")+'>'+e(x)+'</option>';}).join("")+"</select>";else control='<input id="'+id+'" value="'+e(value)+'">';return'<div class="field'+(options.full?" full":"")+'"><label class="'+(options.required?"required":"")+'" for="'+id+'">'+e(label)+'</label>'+control+(options.help?'<small>'+e(options.help)+'</small>':"")+"</div>";}
  function shell(step,body){var meta=window.CMMS_CATALOGS.steps[step];return'<section class="step-view"><header class="step-heading"><div><span class="eyebrow">Paso '+step+" · Tratamiento y aplicación</span><h1>"+e(meta.question)+"</h1><p>"+e(meta.why)+'</p></div><span class="stage-badge">Implementado · P04.4</span></header>'+body+'<button class="link-button" type="button" data-rules>Ver datos y reglas</button></section>';}
  function treatment(state){
    var selected=state.proposedTasks.filter(function(t){return t.id===state.uiState.selectedTaskId;})[0]||state.proposedTasks[0],taskMode=state.uiState.treatmentMode!=="decision";
    var selector='<div class="segmented" aria-label="Tipo de tratamiento"><button class="segment'+(taskMode?" active":"")+'" data-treatment-mode="task" type="button">Tarea propuesta</button><button class="segment'+(!taskMode?" active":"")+'" data-treatment-mode="decision" type="button">Decisión sin tarea</button></div>';
    var body=selector+(taskMode?taskEditor(state,selected):decisionEditor(state))+coverage(state);
    return shell(7,body);
  }
  function taskEditor(state,t){
    var list=state.proposedTasks.map(function(task){return'<button class="task-item'+(t&&task.id===t.id?" active":"")+'" type="button" data-task-id="'+e(task.id)+'"><span class="task-type">'+e(task.type)+'</span><strong>'+e(task.id)+" · "+e(task.title)+'</strong><span>'+e(task.frequency)+" · "+e(task.modeIds.join(", "))+"</span></button>";}).join("");
    var checks=allModes(state).map(function(x){return'<label class="mode-check"><input type="checkbox" data-task-mode-id="'+e(x.mode.id)+'" '+(t.modeIds.indexOf(x.mode.id)>=0?"checked":"")+'><span><strong>'+e(x.mode.id)+" · "+e(x.failure.id)+'</strong><span>'+e(x.mode.hidden?"Fallo oculto":"Modo evidente")+"</span></span></label>";}).join("");
    var check=window.CMMS_TREATMENT_VALIDATIONS.task(t);
    return'<div class="treatment-layout"><aside class="support-panel"><h2>Tareas propuestas</h2><div class="task-list">'+list+'</div><div class="form-actions"><button id="newTask" class="button button-secondary" type="button">Nueva tarea</button></div></aside><section class="form-panel"><input id="taskId" type="hidden" value="'+e(t.id)+'"><h2>Recomendación de ingeniería</h2><div class="engineering-note"><strong>No es un Job Plan, una estrategia, un PM ni una orden.</strong> Requiere validación y conversión gobernada posterior.</div><div class="form-grid" style="margin-top:14px">'+field("Actividad","taskTitle",t.title,{required:true,full:true})+field("Tipo","taskType",t.type,{values:catalogs.taskTypes})+field("Técnica","taskTechnique",t.technique,{values:catalogs.techniques})+field("Frecuencia o disparador","taskFrequency",t.frequency,{required:true})+field("Fundamento","taskFoundation",t.foundation,{required:true,full:true,type:"textarea"})+field("Estado operacional","taskOperationalState",t.operationalState,{values:catalogs.operationalStates})+field("Disciplina","taskDiscipline",t.discipline,{values:catalogs.disciplines})+field("Rol ejecutor","taskRole",t.role,{values:catalogs.roles})+field("Criterio de aceptación","taskCriterion",t.acceptanceCriterion,{required:true,full:true,type:"textarea"})+field("Evidencia requerida","taskEvidence",t.evidenceRequired,{full:true})+'</div><div class="field full" style="margin-top:14px"><label class="required">Modos tratados</label><div class="mode-checks">'+checks+'</div></div><div style="margin-top:14px">'+validation(check,"Tarea completa")+'</div><div class="form-actions"><button id="saveTask" class="button button-primary" type="button">Guardar tarea</button></div></section></div>';
  }
  function decisionEditor(state){
    var modes=allModes(state),decisions=state.noTaskDecisions.map(function(d){return'<div class="decision-card"><strong>'+e(d.id)+" · "+e(d.type)+'</strong><span>'+e(d.modeId)+" · "+e(d.justification)+'</span></div>';}).join("")||'<div class="empty-state">No hay decisiones sin tarea registradas.</div>';
    var modeOptions=modes.map(function(x){return x.mode.id;});
    return'<div class="treatment-layout"><aside class="support-panel"><h2>Decisiones registradas</h2><div class="decision-list">'+decisions+'</div></aside><section class="form-panel"><h2>Alternativa explícita sin tarea periódica</h2><div class="engineering-note">Utiliza esta ruta cuando la decisión RCM adoptada sea operar hasta fallo, rediseñar o declarar que no existe tarea eficaz. El modo nunca queda sin decisión.</div><div class="form-grid" style="margin-top:14px">'+field("Modo","decisionMode",modeOptions[0],{values:modeOptions,required:true})+field("Decisión","decisionType",catalogs.noTaskTypes[0],{values:catalogs.noTaskTypes,required:true})+field("Justificación","decisionJustification","",{type:"textarea",required:true,full:true})+field("Condiciones y límites","decisionConditions","",{type:"textarea",full:true})+'</div><div class="form-actions"><button id="saveNoTaskDecision" class="button button-primary" type="button">Registrar decisión</button></div></section></div>';
  }
  function validation(check,ok){return'<div class="validation-box'+(check.valid?"":" error")+'"><strong>'+(check.valid?ok:"Requiere atención")+'</strong>'+(check.valid?"<span>Relaciones y fundamento documentados.</span>":"<ul>"+check.errors.map(function(x){return"<li>"+e(x)+"</li>";}).join("")+"</ul>")+"</div>";}
  function coverage(state){
    var modes=allModes(state),rows=state.proposedTasks.map(function(t){return'<tr><td><strong>'+e(t.id)+'</strong><br>'+e(t.title)+'</td>'+modes.map(function(x){return'<td class="'+(t.modeIds.indexOf(x.mode.id)>=0?"covered":"empty")+'">'+(t.modeIds.indexOf(x.mode.id)>=0?"Vinculada":"—")+"</td>";}).join("")+"</tr>";}).join("");
    var overall=window.CMMS_TREATMENT_VALIDATIONS.all(state);
    return'<section class="tree-panel"><h2>Cobertura modo-tarea</h2><div class="table-wrap"><table class="data-table coverage-table"><thead><tr><th>Tarea</th>'+modes.map(function(x){return"<th>"+e(x.mode.id)+"</th>";}).join("")+'</tr></thead><tbody>'+rows+'</tbody></table></div><div style="margin-top:12px">'+validation(overall,"Todos los modos tienen tratamiento")+"</div></section>";
  }
  function applicability(state){
    state.assetApplications.forEach(function(a){a.suggestedResult=window.CMMS_APPLICABILITY_ENGINE.suggest(a).result;});
    var rules=state.applicabilityRules.map(function(r){return'<div class="rule-card"><strong>'+e(r.field)+" · "+e(r.operator)+'</strong><span>'+e(r.value)+" → "+e(r.effect)+'</span></div>';}).join("");
    var profiles=catalogs.profiles.map(function(p){return'<div class="profile-card"><strong>'+e(p.name)+'</strong><span>'+e(p.effect)+'</span></div>';}).join("");
    var rows=state.assetApplications.map(function(a){var check=window.CMMS_APPLICABILITY_ENGINE.validate(a),suggestion=check.suggestion,cls=suggestion.result==="No aplicable"?" no":suggestion.result==="Parcial"?" partial":"";return'<tr data-asset-row="'+e(a.id)+'"><td><strong>'+e(a.id)+'</strong><div class="trace-meta">'+e(a.context)+'</div></td><td>'+e(a.criticality)+'</td><td><span class="app-result'+cls+'">'+e(suggestion.result)+'</span><div class="trace-meta">'+e(suggestion.reason)+'</div></td><td><select class="decision-select" data-human-decision>'+catalogs.applicabilityResults.map(function(x){return'<option'+(x===a.humanDecision?" selected":"")+'>'+e(x)+'</option>';}).join("")+'</select></td><td><input class="reason-input" data-human-reason value="'+e(a.reason)+'"><div class="trace-meta">'+e(a.validatedBy)+" · "+e(a.validatedAt)+'</div></td><td>'+e(catalogs.profiles.filter(function(p){return p.id===a.profileId;})[0].name)+'</td></tr>';}).join("");
    var invalid=[];state.assetApplications.forEach(function(a){window.CMMS_APPLICABILITY_ENGINE.validate(a).errors.forEach(function(x){invalid.push(a.id+": "+x);});});
    var check={valid:!invalid.length,errors:invalid};
    return shell(8,'<section class="tree-panel"><h2>Reglas utilizadas</h2><div class="rules-band">'+rules+'</div></section><section class="tree-panel"><h2>Perfiles sin duplicar el AMEF</h2><div class="profile-grid">'+profiles+'</div></section><section class="tree-panel"><div class="step-heading"><div><h2>Aplicabilidad por activo</h2><p>La sugerencia es explicable; la decisión humana conserva usuario, fecha y motivo.</p></div><button id="saveApplicability" class="button button-primary" type="button">Guardar validación</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Activo</th><th>Criticidad</th><th>Sugerencia</th><th>Decisión humana</th><th>Motivo y trazabilidad</th><th>Perfil</th></tr></thead><tbody>'+rows+'</tbody></table></div><div style="margin-top:12px">'+validation(check,"Aplicabilidad validada")+"</div></section>");
  }
  function value(id){var node=document.getElementById(id);return node?node.value.trim():"";}
  function bind(step,state,refresh,notify){
    document.querySelectorAll("[data-treatment-mode]").forEach(function(b){b.addEventListener("click",function(){state.uiState.treatmentMode=b.dataset.treatmentMode;refresh();});});
    document.querySelectorAll("[data-task-id]").forEach(function(b){b.addEventListener("click",function(){state.uiState.selectedTaskId=b.dataset.taskId;refresh();});});
    var newTask=document.getElementById("newTask");if(newTask)newTask.addEventListener("click",function(){var id="TASK-"+String(state.proposedTasks.length+1).padStart(3,"0");state.proposedTasks.push({id:id,title:"",type:catalogs.taskTypes[0],technique:catalogs.techniques[0],description:"",modeIds:[],frequency:"",foundation:"",operationalState:catalogs.operationalStates[0],discipline:catalogs.disciplines[0],role:catalogs.roles[0],duration:"",resources:"",acceptanceCriterion:"",evidenceRequired:"",technicalLimits:"",justification:"",status:"Propuesta"});state.uiState.selectedTaskId=id;refresh();});
    var saveTask=document.getElementById("saveTask");if(saveTask)saveTask.addEventListener("click",function(){var t=state.proposedTasks.filter(function(x){return x.id===value("taskId");})[0];Object.assign(t,{title:value("taskTitle"),description:value("taskTitle"),type:value("taskType"),technique:value("taskTechnique"),frequency:value("taskFrequency"),foundation:value("taskFoundation"),operationalState:value("taskOperationalState"),discipline:value("taskDiscipline"),role:value("taskRole"),acceptanceCriterion:value("taskCriterion"),evidenceRequired:value("taskEvidence")});t.modeIds=Array.from(document.querySelectorAll("[data-task-mode-id]:checked")).map(function(x){return x.dataset.taskModeId;});commit("Tarea propuesta guardada.");});
    var saveDecision=document.getElementById("saveNoTaskDecision");if(saveDecision)saveDecision.addEventListener("click",function(){var candidate={id:"DEC-"+String(state.noTaskDecisions.length+1).padStart(3,"0"),modeId:value("decisionMode"),type:value("decisionType"),justification:value("decisionJustification"),conditions:value("decisionConditions"),status:"Propuesta",author:"Laura Martín · Fiabilidad",date:"2026-07-30"},check=window.CMMS_TREATMENT_VALIDATIONS.decision(candidate);if(!check.valid)return notify(check.errors[0]);state.noTaskDecisions.push(candidate);commit("Decisión sin tarea registrada.");});
    var saveApp=document.getElementById("saveApplicability");if(saveApp)saveApp.addEventListener("click",function(){document.querySelectorAll("[data-asset-row]").forEach(function(row){var a=state.assetApplications.filter(function(x){return x.id===row.dataset.assetRow;})[0],decision=row.querySelector("[data-human-decision]").value,reason=row.querySelector("[data-human-reason]").value.trim();a.humanDecision=decision;a.reason=reason;a.suggestedResult=window.CMMS_APPLICABILITY_ENGINE.suggest(a).result;a.validatedBy="Carlos Vega · Ingeniería de mantenimiento";a.validatedAt="2026-07-30";});var errors=[];state.assetApplications.forEach(function(a){window.CMMS_APPLICABILITY_ENGINE.validate(a).errors.forEach(function(x){errors.push(a.id+": "+x);});});if(errors.length)return notify(errors[0]);commit("Aplicabilidad validada y guardada.");});
    function commit(message){window.CMMS_STORE.markDirty();refresh();notify(message);}
  }
  window.CMMS_P044={render:function(step,state){return step===7?treatment(state):applicability(state);},bind:bind,validate:function(step,state){if(step===7)return window.CMMS_TREATMENT_VALIDATIONS.all(state);var errors=[];state.assetApplications.forEach(function(a){window.CMMS_APPLICABILITY_ENGINE.validate(a).errors.forEach(function(x){errors.push(a.id+": "+x);});});return{valid:!errors.length,errors:errors};}};
})();
