(function(){
  "use strict";
  var e=function(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c];});};
  function allModes(state){var out=[];state.functions.forEach(function(fn){fn.functionalFailures.forEach(function(ff){ff.failureModes.forEach(function(mode){out.push({fn:fn,failure:ff,mode:mode});});});});return out;}
  function shell(body){var meta=window.CMMS_CATALOGS.steps[9];return'<section class="step-view">'+(body.readonly?'<div class="readonly-banner">Revisión publicada · modo solo lectura. Para modificarla, crea la revisión siguiente.</div>':"")+'<header class="step-heading"><div><span class="eyebrow">Paso 9 · Gobierno y trazabilidad</span><h1>'+e(meta.question)+'</h1><p>'+e(meta.why)+'</p></div><span class="stage-badge">Implementado · P04.5</span></header><div class="review-tabs"><button class="review-tab'+(body.tab==="review"?" active":"")+'" data-review-tab="review" type="button">Revisión y aprobación</button><button class="review-tab'+(body.tab==="trace"?" active":"")+'" data-review-tab="trace" type="button">Trazabilidad extremo a extremo</button></div>'+body.html+'<button class="link-button" type="button" data-rules>Ver datos y reglas</button></section>';}
  function render(state){
    var tab=state.uiState.reviewTab||"review",readonly=state.analysisHeader.status==="Publicada";
    return shell({tab:tab,readonly:readonly,html:tab==="trace"?traceability(state):review(state)});
  }
  function review(state){
    var check=window.CMMS_REVIEW_VALIDATIONS.validate(state),modes=allModes(state),approved=state.approvalStages.filter(function(x){return x.status==="Aprobada";}).length;
    var metrics='<div class="executive-grid"><div class="executive-metric"><span>Funciones</span><strong>'+state.functions.length+'</strong></div><div class="executive-metric"><span>Modos analizados</span><strong>'+modes.length+'</strong></div><div class="executive-metric"><span>Tareas propuestas</span><strong>'+state.proposedTasks.length+'</strong></div><div class="executive-metric"><span>Activos evaluados</span><strong>'+state.assetApplications.length+'</strong></div></div>';
    var stages='<div class="approval-timeline">'+state.approvalStages.map(function(s,i){var cls=s.status==="Aprobada"?" approved":s.status==="Devuelta"?" returned":"";return'<div class="approval-stage'+cls+'"><span class="approval-marker">'+(s.status==="Aprobada"?"✓":i+1)+'</span><div class="approval-copy"><strong>'+e(s.name)+" · "+e(s.status)+'</strong><span>'+e(s.actor||"Pendiente de asignación")+(s.date?" · "+e(s.date):"")+'</span>'+(s.comment?'<p>'+e(s.comment)+'</p>':"")+"</div></div>";}).join("")+"</div>";
    var validation='<div class="publish-block"><strong>Validación global</strong><p class="muted">'+(check.errors.length?check.errors.length+" errores críticos":"Sin errores críticos")+" · "+check.warnings.length+" etapas pendientes</p>"+(check.errors.length?'<ul class="critical-list">'+check.errors.map(function(x){return"<li>"+e(x)+"</li>";}).join("")+"</ul>":"")+"</div>";
    var snapshot=state.analysisHeader.snapshotId?'<div class="snapshot"><span>Snapshot simulado</span><strong>'+e(state.analysisHeader.snapshotId)+'</strong><span>Publicado '+e(state.analysisHeader.publishedAt)+" · revisión inmutable</span></div>":"";
    var actions=state.analysisHeader.status==="Publicada"?'<div class="review-actions"><button id="createRevision" class="button button-primary" type="button">Crear revisión siguiente</button></div>':'<div class="field full"><label for="reviewComment">Comentario de devolución</label><textarea id="reviewComment" placeholder="Obligatorio al devolver una etapa"></textarea></div><div class="review-actions"><button id="saveReviewDraft" class="button button-secondary" type="button">Guardar borrador</button><button id="returnReview" class="button button-secondary" type="button">Devolver con comentarios</button><button id="sendReview" class="button button-secondary" type="button">Enviar a revisión</button><button id="approveStage" class="button button-primary" type="button">Aprobar siguiente etapa</button><button id="publishReview" class="button button-primary" type="button" '+(check.canPublish?"":"disabled")+'>Publicar simulación</button></div>';
    var modeSummary=modes.map(function(x){return'<tr><td>'+e(x.mode.id)+'</td><td>'+e(x.mode.rcmAssessment.recommendation)+'</td><td>'+e(x.mode.rcmAssessment.override?x.mode.rcmAssessment.adoptedDecision:x.mode.rcmAssessment.recommendation)+'</td><td>'+e(state.proposedTasks.filter(function(t){return t.modeIds.indexOf(x.mode.id)>=0;}).length)+" tareas</td></tr>";}).join("");
    return metrics+'<div class="review-layout"><section class="review-section"><h2>Resumen de decisiones</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Modo</th><th>Recomendación RCM</th><th>Decisión adoptada</th><th>Cobertura</th></tr></thead><tbody>'+modeSummary+'</tbody></table></div><div class="engineering-note" style="margin-top:12px">La publicación prepara una conexión futura y gobernada con estrategias y Job Plans. No crea ningún objeto de mantenimiento.</div><h2 style="margin-top:18px">Registro de cambios</h2>'+changeLog(state)+'</section><aside class="review-section"><h2>Aprobaciones · '+approved+" de "+state.approvalStages.length+'</h2>'+stages+validation+snapshot+actions+"</aside></div>";
  }
  function changeLog(state){return'<div class="change-list">'+state.changeLog.slice().reverse().map(function(c){return'<div class="change-item"><span>'+e(c.date)+'</span><div><strong>'+e(c.action)+'</strong><span>'+e(c.user)+" · "+e(c.detail)+'</span></div></div>';}).join("")+"</div>";}
  function traceability(state){
    var rows=[],h=state.analysisHeader;
    rows.push(row("Revisión AMEF",h.id,h.title,h.status,h.revision,"Fuente funcional y equipo de fiabilidad"));
    state.functions.forEach(function(fn){rows.push(row("Función",fn.id,fn.description,"Completa",h.revision,fn.source));fn.functionalFailures.forEach(function(ff){rows.push(row("Fallo funcional",ff.id,ff.description,"Completo",h.revision,ff.detectionCondition));ff.failureModes.forEach(function(mode){rows.push(row("Modo",mode.id,mode.description,"Analizado",h.revision,mode.historicalEvidence));mode.causes.forEach(function(c){rows.push(row("Causa",c.id,c.description,"Documentada",h.revision,c.evidence));});mode.effects.forEach(function(x){rows.push(row("Efecto",x.id,x.description,"Documentado",h.revision,x.level));});var risk=window.CMMS_RISK_ENGINE.calculate(mode.consequenceAssessment.severity,mode.consequenceAssessment.probability);rows.push(row("Riesgo",mode.id+"-RISK",risk.score+" · "+risk.level.label,"Calculado",mode.consequenceAssessment.matrixVersion,mode.consequenceAssessment.justification));rows.push(row("Decisión RCM",mode.id+"-RCM",mode.rcmAssessment.recommendation,"Adoptada",mode.rcmAssessment.treeVersion,Object.keys(mode.rcmAssessment.responses).length+" respuestas con evidencia"));state.proposedTasks.filter(function(t){return t.modeIds.indexOf(mode.id)>=0;}).forEach(function(t){rows.push(row("Tarea propuesta",t.id,t.title,t.status,h.revision,t.foundation));});});});});
    state.assetApplications.forEach(function(a){rows.push(row("Activo aplicable",a.id,a.context,a.humanDecision,h.revision,a.reason+" · "+a.validatedBy));});
    state.approvalStages.forEach(function(a){rows.push(row("Aprobación",a.id,a.name,a.status,h.revision,a.actor||"Pendiente"));});
    return'<section class="review-section"><div class="step-heading"><div><h2>Cadena trazable de la revisión</h2><p>Cada nodo conserva identidad, estado, versión y evidencia simulada.</p></div><span class="stage-badge">'+rows.length+" nodos</span></div><div class=\"trace-chain\">"+rows.join("")+'</div><div class="future-output"><strong>Futura salida gobernada</strong><p>Revisión publicada → recomendación de ingeniería → proceso de conversión de IT → estrategia / Job Plan / PM. Este prototipo termina antes de la conversión.</p></div></section>';
  }
  function row(kind,id,label,status,version,evidence){return'<div class="trace-row"><div><span class="trace-kind">'+e(kind)+'</span><div class="trace-status">'+e(id)+'</div></div><div class="trace-main"><strong>'+e(label)+'</strong><span>'+e(evidence||"Sin evidencia adicional")+'</span></div><div class="trace-status">'+e(status)+'</div><div class="trace-meta-cell">Versión '+e(version)+'<br>2026-07-30</div></div>';}
  function bind(step,state,refresh,notify){
    document.querySelectorAll("[data-review-tab]").forEach(function(b){b.addEventListener("click",function(){state.uiState.reviewTab=b.dataset.reviewTab;refresh();});});
    var save=document.getElementById("saveReviewDraft");if(save)save.addEventListener("click",function(){state.analysisHeader.status="Borrador";log(state,"Borrador guardado","Revisión "+state.analysisHeader.revision);commit("Borrador de revisión guardado.");});
    var send=document.getElementById("sendReview");if(send)send.addEventListener("click",function(){state.analysisHeader.status="En revisión";log(state,"Análisis enviado a revisión","Revisión "+state.analysisHeader.revision);commit("Análisis enviado a revisión.");});
    var approve=document.getElementById("approveStage");if(approve)approve.addEventListener("click",function(){if(state.analysisHeader.status!=="En revisión")return notify("Envía primero el análisis a revisión.");var next=state.approvalStages.filter(function(x){return x.status!=="Aprobada";})[0];if(!next)return notify("Todas las etapas ya están aprobadas.");next.status="Aprobada";next.actor="Usuario demo · "+next.name;next.date="2026-07-30";next.comment="Etapa aprobada en la simulación.";log(state,"Etapa aprobada",next.name);commit(next.name+" aprobada.");});
    var returned=document.getElementById("returnReview");if(returned)returned.addEventListener("click",function(){var comment=document.getElementById("reviewComment").value.trim();if(!comment)return notify("Escribe un comentario antes de devolver.");var current=state.approvalStages.filter(function(x){return x.status!=="Aprobada";})[0]||state.approvalStages[state.approvalStages.length-1];current.status="Devuelta";current.actor="Usuario demo · Revisor";current.date="2026-07-30";current.comment=comment;state.analysisHeader.status="Devuelta";log(state,"Etapa devuelta",current.name+" · "+comment);commit("Etapa devuelta con comentarios.");});
    var publish=document.getElementById("publishReview");if(publish)publish.addEventListener("click",function(){var check=window.CMMS_REVIEW_VALIDATIONS.validate(state);if(!check.canPublish)return notify(check.errors[0]||check.warnings[0]||"La revisión no está lista.");state.analysisHeader.status="Publicada";state.analysisHeader.snapshotId="SNAP-"+state.analysisHeader.id+"-R"+state.analysisHeader.revision.replace(".","");state.analysisHeader.publishedAt="2026-07-30 15:30";log(state,"Revisión publicada",state.analysisHeader.snapshotId);window.CMMS_STORE.markDirty();window.CMMS_STORE.save();refresh();notify("Revisión publicada en modo solo lectura.");});
    var nextRevision=document.getElementById("createRevision");if(nextRevision)nextRevision.addEventListener("click",function(){var previous=state.analysisHeader.snapshotId,revision=(Number(state.analysisHeader.revision)+0.1).toFixed(1);state.analysisHeader.previousSnapshotId=previous;state.analysisHeader.revision=revision;state.analysisHeader.status="Borrador";state.analysisHeader.snapshotId=null;state.analysisHeader.publishedAt=null;state.approvalStages.forEach(function(s){s.status="Pendiente";s.actor="";s.date="";s.comment="";});log(state,"Nueva revisión creada","Revisión "+revision+" desde "+previous);commit("Revisión "+revision+" creada y desbloqueada.");});
    function commit(message){window.CMMS_STORE.markDirty();refresh();notify(message);}
  }
  function log(state,action,detail){state.changeLog.push({id:"CHG-"+String(state.changeLog.length+1).padStart(3,"0"),date:"2026-07-30",user:"Usuario demo",action:action,detail:detail});}
  window.CMMS_P045={render:function(step,state){return render(state);},bind:bind,validate:function(step,state){return window.CMMS_REVIEW_VALIDATIONS.validate(state);}};
})();
